#!/usr/bin/env bash
# transfers a file from our client to a server
if [ $# -lt 3 ];
then 
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
file_path=$1
ip_address=$2
usr_name=$3
private_key_path=$4

scp -o StrictHostKeyChecking=no -i "$private_key_path" "$file_path" "$usr_name@$ip_address:~/" 
