#!/usr/bin/env bash
# configures a brand new Ubuntu machine to the requirements asked in this task
apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html

sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sed -i '/listen 80 default_server/a error_page 404 /404.html; location = /404.html {root /usr/share/nginx/html;\n internal;}' /etc/nginx/sites-available/default

sed -i "X-Served-By: $(hostname)" /etc/nginx/sites-available/default

sudo service nginx restart
