#!/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it.

sudo mysqldump -uroot -p --all-databases > backup.sql
tar -czvf day-month-year.tar.gz backup.sql
sudo mysql -uroot -p"$1"
