#!/usr/bin/env bash
#bashscript loops through 1 to 10

i=1

while [ $i -le 10 ]
do
  if [ $i -eq 4 ]
  then
     echo "bad luck"
  elif [ $i -eq 8 ]
  then
     echo "good luck"
  fi
  echo "Best School"
  ((i++))
done
