#!/usr/bin/env bash
#school
if [ -e school ]
then
	echo "school file exists"

	if [ -s school -eq 0 ]
         then
		 echo "school file is empty"
	 elif [ -s school -gt 0 ]
	 then
		echo "school file is not empty"
	  fi

	if [ -f school ] 
	 then
		echo "school is a regular file"
	  fi
else
	echo "school file does not exist"
fi
