#!/usr/bin/env bash
# set user to nginx and lisen port 8080

sudo adduser --system --no-create-home --disabled-login --group nginx
sudo sed -i 's/#user nginx;/user nginx;/g' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80;/listen 8080 default_server;/g' /etc/nginx/nginx.conf
sudo systemctl restart nginx
